# Basic
title: 战乱之剑
subtitle: 寄
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">下载主题</a>
description: “吾心吾行澄如明镜，所作所为皆为正义”
creator: <a href="http://Fe2345.github.io">@SwordOfWar</a>

url: "http://github.com/Fe2345/Fe2345.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 文章
    description: 查看文章

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'http://github.com/Fe2345'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
